### ISSUE TITLE
Hacktoberfest 2018 Yay!

### ISSUE THREAD

**Issue by HoussemCharf** [HoussemCharf/FunUtils#15]
Hello contributors 

Thank you all for swinging by, in the spirit of Hacktoberfest I'd like to invite y'all to contribute to this folder with your cool python scripts 

yep it's as easy as that, Happy hacking every buddy 😄

**Comment by Baev1** [comment]
mind if I make and add a script that you can use to query https://spoopy.link/ to see if the link is safe?

**Comment by faouziamrouche** [comment]
@HoussemCharf I added the KnighL script, check it out

**Comment by Utkarsh1308** [comment]
I added the Scrabble Cheater Script. Check it out
