### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by HoussemCharf** [HoussemCharf/FunUtils#3]
It's simple people all you have to do is submit a **helpful** python code
GL & HF!

**Comment by mohamed-aziz** [comment]
Hey, Can Emacs Lisp snippets be submitted ?

**Comment by HoussemCharf** [comment]
only **python** that's the rule sorry.

**Comment by satishm752** [comment]
can I submit python code for sorting, dfs, bfs, etc?

**Comment by HoussemCharf** [comment]
@satishm752 sure add it under a sorting algorithms folder

**Comment by mohamed-aziz** [comment]
@HoussemCharf nice I have some interesting algorithmic solutions from http://codeabbey.com  in my hard drive I will submit them. BTW I'm also form Tunisia.

**Comment by HoussemCharf** [comment]
@mohamed-aziz it's always a pleasure to find weld bled 💙 looking forward for those PR 👍

**Comment by talsperre** [comment]
@HoussemCharf I have a few python scripts related to web scraping and backing up files. One of them will download bing wallpaper of the day and the other one is for scraping xkcd comics. Would those do?

**Comment by HoussemCharf** [comment]
@talsperre yes they are eligible 👍
